= CloudBees action: Fetch secrets from CyberArk Conjur

Use this action to fetch secrets from CyberArk Conjur, a tool that securely stores and retrieves sensitive information, such as passwords and API keys.
Fetched secret output is masked in CloudBees platform and is not logged or accessed by background processes, so it can be used securely in a downstream step of the same job.

== Inputs

[cols="14%a,9%a,12%a,65%a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `login`
| String
| Yes
| The host username required to sign in to Conjur.

| `api-key`
| String
| Yes
| The API key for generating a short-lived access token for authentication.

| `url`
| String
| Yes
| The CyberArk Conjur server URL.

| `variables`
| String
| Yes
| A comma-separated list of the full paths of each secret to be fetched.

|===

== Output

[cols="2a,2a,3a",options="header"]
.Output details
|===

| Output name
| Data type
| Description

| `conjur_output`
| JSON string
| The value of each fetched secret, in JSON format.
[#slash]
NOTE: Any forward slashes (`+/+`) in the `variables` input are replaced with underscores (`+_+`) by CloudBees platform in the output, so to refer to full paths, you must replace `+/+` with `+_+`.

|===

== Usage examples

=== Basic example

The following is a basic example of using this action:

[source,yaml,role="default-expanded"]
----

    steps:
      - name: Fetch secrets from Conjur
        uses: cloudbees-io/cyberark-conjur-fetch-secrets@v1
        with:
          login: ${{ secrets.CONJUR_USERNAME }}
          api-key: 12345-abcde-67890-fghij-12345
          url: https://my-conjur.example.com
          variables: full/path/to/secret-1,full/path/to/secret-2

----

=== Using the action output

Access the `conjur_output` values in downstream steps of the same job using the `outputs` xref:dsl-syntax:contexts.adoc[context].
If you want to use the same secrets in another job, you must call the Conjur action again in that job.
Use the `conjur_output` output for a single secret value as follows, where `<action_step_ID>` is the action step ID, and `<full_path_no_slashes>` is the full path of the secret, with any `+/+` replaced with `+_+`:

[source,yaml]
----

${{ fromJSON(steps.<action_step_ID>.outputs.conjur_output).<full_path_no_slashes> }}

----

In the following example, the action output is used in a downstream step of the same job.

NOTE: Each `echo` command outputs `\***` in place of the secret, because the action masks all fetched secrets.

[source,yaml,role="default-expanded"]
----

jobs:
  use-conjur-secrets:
    steps:
      - name: Fetch secrets from Conjur
        id: fetch-my-secrets
        uses: cloudbees-io/cyberark-conjur-fetch-secrets@v1
        with:
          login: ${{ secrets.YOUR_CONJUR_USERNAME }}
          api-key: ${{ secrets.YOUR_CONJUR_API_KEY }}
          url: ${{ vars.YOUR_CONJUR_URL }}
          variables: my-org/my-directory/secret1,my-org/my-directory/secret2

      - name: Use fetched secrets
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "Secret1 is fetched but masked: ${{ fromJSON(steps.fetch-my-secrets.outputs.conjur_output).my-org_my-directory_secret1 }}"
          echo "Secret2 is fetched but masked: ${{ fromJSON(steps.fetch-my-secrets.outputs.conjur_output).my-org_my-directory_secret2 }}"

----
== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
